// Custom color scheme
const theme = {
  colors: {
    pool: [
      "anakiwa-bg",
      "atomic-tangerine-bg",
      "bahama-blue-bg",
      "bourbon-bg",
      "blue-bell-bg",
      "chestnut-rose-bg",
      "cosmic-bg",
      "danub-bg",
      "dodger-pale-bg",
      "dodger-soft-bg",
      "eggplant-bg",
      "golden-tanoi-bg",
      "hopbush-bg",
      "husk-bg",
      "indigo-bg",
      "lavender-purple-bg",
      "lilac-bg",
      "mariner-bg",
      "medium-carmine-bg",
      "melrose-bg",
      "navy-blue-bg",
      "near-blue-bg",
      "neon-carrot-bg",
      "orange-peel-bg",
      "pale-canary-bg",
      "periwinkle-bg",
      "alert-bg",
      "red-damask-bg",
      "rust-bg",
      "sandy-brown-bg",
      "tamarillo-bg",
      "tanoi-bg",
    ],
    interactive: [
      "primary-interactive",
      "secondary-interactive",
      "tertiary-interactive",
    ],
    static: ["primary-static", "secondary-static", "tertiary-static"],
    text: {
      dark: "text-dark",
      light: "text-light",
      white: "text-white",
      black: "text-black",
    },
  },
};
